### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by abhigkar** [phaetto/selenium-reinforment-learning#1]
Dear @phaetto ,

I was searching some projects on Selenium +C# for AI/ML and came across your repository. I have gone though the codebase and it looks very interesting.

Just wondering about the status of the project and looking for few more details about how to use or a simple user guide.

Thanks,
Thanks for your awesome work!!!

**Comment by phaetto** [comment]
Hey @abhigkar!

Right now this is just a small research project of mine. Unfortunately because of time constraints, I haven't been able to put more work on it.

The main core functionality is working - you can train an agent to find your goal and present you with a path of actions. I have been using it in work projects for some time now for training and testing (I am using it with an application embedded in SharePoint).

There are however many, and big missing parts:
- Serialization/deserialization of the output so you can reuse it in on some tests
- A kind of runtime that will get information of the existing trained results and allow you to select a test to run, or compose one from the discovered paths
- Quality of life improvements: The application under test should be able to be a part of the page and there needs to be a good way to set that (I think I have several of those in my TODO list)

As a starting point you can look at the tests. One of simplest one is [here](https://github.com/phaetto/selenium-reinforment-learning/blob/master/Selenium.Algorithms.UnitTests/Runs/SimpleTestCaseTests.cs). The tests are only for training though.

**Comment by sudiprai10** [comment]
Hi @phaetto 

Any update on this? I was also looking at this project but could not figure out where to start. Can you help us with any working example for end to end scenarios?

Thanks,
Sudip Rai

**Comment by phaetto** [comment]
Hey @sudiprai10 and @abhigkar
There is now a full end to end example you can run and debug.

Cheers
